dependencies:
- name: onedata-chart-utils
  version: 0.2.10
  repository: https://onedata.github.io/charts/

- name: volume-nfs
  alias: stress-nfs-volume
  version: 0.2.9
  repository: https://onedata.github.io/charts/
