---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
    spec:
      hostname: node1
      subdomain: {{ template "fullname" . }}
{{ include "imagePullSecrets" . | indent 6 }}
      volumes:
      - name: persistence
        emptyDir:
          medium: "Memory"
      - name: posix
        emptyDir:
          medium: "Memory"
      containers:
      - name: {{ .Chart.Name }}
        image: {{ .Values.image }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        resources:
          requests:
            cpu: "2"
            memory: 4Gi
        ports:
          - containerPort: 53
          - containerPort: 80
          - containerPort: 443
          - containerPort: 5555
          - containerPort: 5556
          - containerPort: 6665
          - containerPort: 6666
          - containerPort: 7443
          - containerPort: 8443
          - containerPort: 8876
          - containerPort: 8877
          - containerPort: 9443
        lifecycle:
          preStop:
            exec:
              command:
                - "sh"
                - "-c"
                - >
                  op_panel stop ;
                  op_worker stop ;
                  cluster_manager stop ;
                  /etc/init.d/couchbase-server stop ;
                  pkill -f oneprovider.py ;
        readinessProbe:
          exec:
            command:
              - "/bin/bash"
              - "-c"
              - >
                service=provider ;
                user="$(curl -k -u admin:password -sS --tlsv1.2 -X GET 'https://localhost:9443/api/v3/onepanel/users/user')";
                if [[ "$user" == "" ]] ; then exit 1; else  exit 0;  fi ;
        env:
          - name: ONEPANEL_BATCH_MODE
            value: "true"
          - name: ONEPROVIDER_CONFIG
            value: |
              cluster:
                domainName: "{{ template "service_url" . }}"
                nodes:
                  n1:
                    hostname: "node1"
                managers:
                  mainNode: "n1"
                  nodes:
                    - "n1"
                workers:
                  nodes:
                    - "n1"
                databases:
                  nodes:
                    - "n1"
                storages:
                  posix:
                    type: "posix"
                    mountPoint: "/volumes/storage"
              oneprovider:
                register: true
                name: {{ template "fullname" . }}
                redirectionPoint: "https://{{ template "service_url" . }}"
                geoLatitude: {{ .Values.geoLatitude }}
                geoLongitude: {{ .Values.geoLongitude }}
              onezone:
                domainName: "{{ template "onezone_service_url" . }}"
              onepanel:
                users:
                  "admin":
                    password: "password"
                    userRole: "admin"
                  "user":
                    password: "password"
                    userRole: "regular"
        volumeMounts:
        - mountPath: /volumes/persistence
          name: persistence
        - mountPath: /volumes/storage
          name: posix