dependencies:
- name: onedata-chart-utils
  version: 0.2.11
  repository: https://onedata.github.io/charts/

- name: keycloak
  version: 0.1.3
  repository: https://onedata.github.io/charts/
  condition: keycloak.enabled
  
- name: token-dispenser
  version: 0.1.3
  repository: https://onedata.github.io/charts/
  condition: token-dispenser.enabled