dependencies:
- name: onedata-chart-utils
  version: 0.2.14
  repository: https://onedata.github.io/charts/

- name: keycloak
  version: 0.1.5
  repository: https://onedata.github.io/charts/
  condition: keycloak.enabled
  
- name: elasticsearch
  version: 0.1.1
  repository: https://onedata.github.io/charts/
  condition: elasticsearch.enabled
  
- name: token-dispenser
  version: 0.1.4
  repository: https://onedata.github.io/charts/
  condition: token-dispenser.enabled