dependencies:
- name: onedata-chart-utils
  version: 0.2.8
  repository: https://groundnuty.github.io/onedata-charts/

- name: onedata-1p
  version: 0.2.1
  repository: https://groundnuty.github.io/onedata-charts/
  condition: onedata-1p.enabled