dependencies:
- name: onedata-chart-utils
  version: 0.2.8
  repository: https://onedata.github.io/charts/

- name: onedata-1p
  version: 0.2.1
  repository: https://onedata.github.io/charts/
  condition: onedata-1p.enabled