# Default values for volume ceph.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: ceph/demo:tag-build-master-luminous-ubuntu-16.04
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

cluster_name: ceph # hardcoded  somewhere in the container
username: client.k8s
key: AQC1oSZZZfucFxAA34MekwoWBm7qpGd0A8u+fg==
pool_name: test
