# Default values for onedata-cli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/rest-cli:3.0.0-rc16
imagePullPolicy: IfNotPresent

wait_for:
  image: groundnuty/k8s-wait-for:0.1
  imagePullPolicy: IfNotPresent