# Default values for onedata-cli.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: docker.onedata.org/rest-cli:3.0.0-rc12
imagePullPolicy: IfNotPresent

wait_for:
  image: groundnuty/k8s-wait-for
  imagePullPolicy: IfNotPresent