dependencies:
- name: onedata-chart-utils
  version: 0.2.10
  repository: file://../onedata-chart-utils

- name: onedata-3p
  version: 0.2.11
  repository: file://../onedata-3p
  condition: onedata-3p.enabled  
  import-values:
    - child: onezone.onezone_main_admin
      parent: onedata-3p.onezone.onezoneAdmin
    - child: onezone.keycloak
      parent: keycloakInstance