dependencies:
- name: onezone
  version: 0.2.6
  repository: https://groundnuty.github.io/onedata-charts/

- name: oneprovider
  version: 0.2.5
  repository: https://groundnuty.github.io/onedata-charts/