dependencies:
- name: onezone
  version: 0.1.0
  repository: file://../onezone

- name: oneprovider
  version: 0.1.0
  repository: file://../oneprovider

- name: oneprovider
  alias: oneprovider-1
  version: 0.1.0
  repository: file://../oneprovider

- name: oneprovider
  alias: oneprovider-2
  version: 0.1.0
  repository: file://../oneprovider

- name: onedata-chart-utils
  version: 0.1.0
  repository: file://../onedata-chart-utils