dependencies:
- name: onezone
  version: 0.2.7
  repository: https://onedata.github.io/charts/

- name: oneprovider
  alias: oneprovider-krakow
  version: 0.2.6
  repository: https://onedata.github.io/charts/

- name: oneprovider
  alias: oneprovider-paris
  version: 0.2.6
  repository: https://onedata.github.io/charts/

- name: oneprovider
  alias: oneprovider-lisbon
  version: 0.2.6
  repository: https://onedata.github.io/charts/