dependencies:
- name: onedata-chart-utils
  version: 0.2.9
#  repository: file://../onedata-chart-utils/

- name: saml-idp
  version: 0.2.1
#  repository: file://../saml-idp/
  condition: saml-idp.enabled
