dependencies:
- name: onedata-chart-utils
  version: 0.2.8
  repository: https://onedata.github.io/charts/

- name: saml-idp
  version: 0.2.0
  repository: file://../saml-idp
  condition: saml-idp.enabled