# Default values for onezone.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

image: onedata/onezone:3.0.0-rc16
imagePullPolicy: IfNotPresent
serviceType: ClusterIP

# onezone name, if empty defaults to a chart name
name: ''

# Resources requested by onezone
cpu: 1.5
memory: 4Gi

# Log level of the processes in the container
log_level: "info"

# Enable loading oneozne configuration from ONEZONE_CONFIG env variable
onepanel_batch_mode_enabled: true

# List of onezone onepanel users with administrative privileges
onepanel_admin_users:
  - login: admin
    password: password

# List of onezone onepanel regular users
onepanel_users:
  - login: user
    password: password

saml-idp:
  enabled: false