name: volume-s3
version: 0.1.0
home: https://github.com/onedata/charts
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
description: S3 Scality object storage service, suitable for testing purposes.
engine: gotpl