apiVersion: v1
kind: Pod
metadata:
  name: alpine
spec:
  containers:
  - image: alpine
    name: alpine
    command:
      - sleep
      - "360000"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always
