# ---
# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: example-local-pv
#   labels:
#     type: local-storage
# spec:
#   capacity:
#     storage: 1Gi
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: local-storage
#   local:
#     path: /mnt/volume1/local-persistent-volume
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - k8s-cyfronet-1-node-10
# ---
# kind: PersistentVolumeClaim
# apiVersion: v1
# metadata:
#   name: example-local-claim
# spec:
#   accessModes:
#   - ReadWriteOnce
#   storageClassName: local-storage
#   resources:
#     requests:
#       storage: 20Gi
---
kind: Pod
apiVersion: v1
metadata:
  name: test-pod
spec:
  containers:
  - name: busybox
    image: busybox
    command:
    - /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - mountPath: "/testpvc"
      name: testpvc
  volumes:
  - name: testpvc
    persistentVolumeClaim:
      claimName: example-local-claim