# kind: StorageClass
# apiVersion: storage.k8s.io/v1
# metadata:
#   name: local-storage
# provisioner: kubernetes.io/no-provisioner
# volumeBindingMode: WaitForFirstConsumer
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: c10-volume
# spec:
#   capacity:
#     storage: 60Gi
#   # volumeMode field requires BlockVolume Alpha feature gate to be enabled.
#   accessModes:
#   - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Recycle #Delete
#   storageClassName: local-storage
#   local:
#     path: /mnt/volume1/local-persistent-volume
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - k8s-cyfronet-1-node-10
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ubuntu-persistence
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: cc
spec:
  containers:
  - image: busybox
    env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    name: u
    command:
    - /bin/sh
    - -c
    - sleep 30000
    volumeMounts:
    - name: persistence
      mountPath: /persistence
      subPathExpr: $(POD_NAME)-$(POD_NAME)
  restartPolicy: Always
  volumes:
  - name: persistence
    persistentVolumeClaim:
      claimName: ubuntu-persistence