dependencies:
- name: onezone
  version: 0.2.7
  repository: https://groundnuty.github.io/onedata-charts/

- name: oneprovider
  alias: oneprovider-krakow
  version: 0.2.6
  repository: https://groundnuty.github.io/onedata-charts/