apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "fullname" . }}-init
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}
    release: {{ template "releaseName" . }}
    heritage: {{ .Release.Service }}
    component: {{ .Chart.Name }}
  annotations:
    version: "{{ .Chart.Version }}"
spec:
  template:
    metadata:
      name: {{ template "releaseName" . }}
      labels:
        app: {{ template "fullname" . }}-init
        chart: {{ .Chart.Name }}
        release: {{ template "releaseName" .  }}
        heritage: {{ .Release.Service }}
        component: {{ .Chart.Name }}-init
      annotations:
        version: "{{ .Chart.Version }}"
    spec:
      hostNetwork: {{ template "hostNetwork" . }}
      {{- if .Values.affinity }}
      affinity:
{{ toYaml .Values.affinity | indent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations:
{{ toYaml .Values.tolerations | indent 8 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}
      {{- end }}  
      restartPolicy: Never
{{ include "imagePullSecrets" . | indent 6 }}
      {{- if (index .Values "wait_for_swift" "enabled") }}
      initContainers:
      {{- end }}
      {{- if (index .Values "wait_for_swift" "enabled") }}
        - name: wait-for-{{ .Chart.Name }}
          image: {{ .Values.wait_for.image }}
          imagePullPolicy: {{ template "imagePullPolicy" dict "root" . "context" .Values.wait_for }}
          args:
            - "pod"
            - "-lapp={{ template "fullname" . }}"
      {{- end }}
      containers:
      - name: swift
        image: {{ .Values.image }}
        imagePullPolicy: {{ template "imagePullPolicy" dict "root" . }}
        command:
          - "/bin/bash"
          - "-c"
          - >
            swift --auth-version 2 -A http://{{ template "volume-swift_name" . }}:5000/v2.0 -K swift -U swift --os-tenant-name service post {{ .Values.containerName }} ;
