name: stress-experiment
version: 0.1.0
description: Orchestrator for stress-suites.
keywords:
  - onedata
  - benchmark
  - tests
  - runner
home: https://github.com/onedata/charts
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
engine: gotpl