name: oneprovider
version: 0.1.0
home: https://github.com/onedata/onedata
maintainers:
  - name: Michal Orzechowski
    email: orzechowski.michal@gmail.com
description: The main data management component of Onedata, deployed at each storage provider site, responsible for unifying and controlling access to data over low level storage resources of the provider.
engine: gotpl