dependencies:
- name: oneclient
  version: 0.2.7
  repository: https://onedata.github.io/charts/
  condition: oneclient.enabled

- name: onedata-cli
  version: 0.2.7
  repository: https://onedata.github.io/charts/
  condition: onedata-cli.enabled

- name: onedata-chart-utils
  version: 0.2.8
  repository: https://onedata.github.io/charts/

- name: volume-s3
  version: 0.2.3
  repository: https://onedata.github.io/charts/
  condition: volume-s3.enabled

- name: volume-ceph
  version: 0.2.3
  repository: https://onedata.github.io/charts/
  condition: volume-ceph.enabled

- name: volume-nfs
  version: 0.2.4
  repository: https://onedata.github.io/charts/
  condition: volume-nfs.enabled

- name: volume-gluster
- name: volume-swift
  version: 0.2.0
  repository: file://../volume-swift
  condition: volume-swift.enabled
