dependencies:
- name: oneclient
  version: 0.2.1
  repository: https://groundnuty.github.io/onedata-charts/
  condition: oneclient.enabled

- name: onedata-cli
  version: 0.2.1
  repository: https://groundnuty.github.io/onedata-charts/
  condition: onedata-cli.enabled

- name: onedata-chart-utils
  version: 0.2.3
  repository: https://groundnuty.github.io/onedata-charts/
